Add SerializationCatchError example
trifork/cheetah-example-flink pull request #70
Opened 2023-11-13 09:50 UTC by dattrifork

This example demonstrates a customized approach to handling deserialization errors, where a log message is presented alongside an incrementing metric counter, as opposed to the of the job throwing an exception and terminating.

To achieve this, a implementation of the Deserialization method extending JsonDeserializationSchema is necessary. This custom method outputs null in the event of a deserialization error, rather than triggering an exception and potentially crashing the job.

The rationale behind returning null from the deserialization method, instead of directly incrementing the metric count, is because we don't have access to the RunTimeContext within the deserialization method. Instead, a RichFilterFunction checks whether the incoming message is null and increments the metric count.

If there exists a more effective approach to accomplish this task, I am open to suggestions. :)

2023-11-13 14:57 UTC, rkthtrifork commented on SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/DeserializationSchema.java
> +            System.out.println("The message failed to be serialized with error message => " + e);
i think we should use log4j instead https://github.com/trifork/cheetah-lib-processing/blob/main/src/main/java/com/trifork/cheetah/processing/auth/CachedTokenProvider.java#L72

2023-11-13 14:58 UTC, rkthtrifork commented on SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/DeserializationSchema.java
> +package cheetah.example.serializationerrorcatch.function;
i would put this in a different package. maybe cheetah.example.serializationerrorcatch.(serde/deserialization)

2023-11-13 15:00 UTC, rkthtrifork commented on SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/DeserializationSchema.java
> +    public void deserialize(byte[] message, Collector<T> out)  {
never mind. i see why now :D

2023-11-13 15:02 UTC, rkthtrifork commented on SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/FilterAndCountFailedSerializations.java
> +            getRuntimeContext()
we should have the gauge as a private field and retrieve it in open, i.e. messagesFailed = getRuntimeContext().getMetricGroup().gauge(...);

2023-11-13 15:04 UTC, rkthtrifork commented on SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/SerializationErrorCatchMapper.java
> +        return new OutputEvent(inputEvent, extraField);
any particular reason we dont just use the same type for input and output events?

2023-11-13 15:18 UTC, rkthtrifork commented on SerializationErrorCatch/src/test/java/cheetah/example/serializationerrorcatch/model/SerializationErrorCatchInputEventTest.java
> +        assertSerializedAsPojo(InputEvent.class);
this is unnecessary since assertSerializedAsPojoWithoutKryo does the same and more

2023-11-13 15:18 UTC, rkthtrifork commented on SerializationErrorCatch/src/test/java/cheetah/example/serializationerrorcatch/model/SerializationErrorCatchOutputEventTest.java
> +        assertSerializedAsPojo(OutputEvent.class);
same as above

2023-11-13 15:20 UTC, rkthtrifork requested changes
comments

2023-11-14 12:30 UTC, rkthtrifork requested changes
i believe log level warn will log everything by default. could be debug og info level if that makes more sense. otherwise all good 👍

2023-11-14 13:13 UTC, dattrifork commented
I believe log level warn is fine in this example as it only happens when the deserialization fails

2023-11-15 14:27 UTC, rkthtrifork approved these changes
👍

2023-11-16 08:53 UTC, merged